# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'instagramclone_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Analytics'
pod 'Firebase/Crashlytics'
pod 'Firebase/Storage'
pod 'Firebase/Firestore'

  # Pods for instagramclone_iOS

end
